### PR TITLE
soroban-rpc: Add common retention window for events and transactions.

### PR DESCRIPTION
**Pull request by psheth9**
### What

Add a config for common retention window for events and transactions

### Why

More detail here: https://github.com/stellar/soroban-rpc/issues/15

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by 2opremio** [comment]
I know it's still a draft, but we shouldn't merge this until we can gauge the storage implications of increasing the tx window to 24 hours.

**Comment by psheth9** [comment]
Yes agreed @2opremio !! I won't merge :) 

I think @stellarsaur already did some initial profiling [here](https://github.com/stellar/soroban-tools/issues/1056#issuecomment-1841875651)  

Do we also want to make sure that retention window should not go beyond 24hrs? or no such upper bound limitation here? cc @mollykarcher (not sure if we are doing that already)

**Comment by 2opremio** [comment]
BTW, isn’t this a dup of #1060 ?

**Comment by leighmcculloch** [comment]
Closing since the rpc has moved to another repo, this change needs taking to that other repo if the change is still relevant.

**Pull request closed without merging**
