### PR TITLE
chore: add test of vec of udt

### LINKED ISSUE #735: CLI parsing error for a relatively basic custom `Vec` type
Given this function interface:
```rust
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MinerColorAmount(
    pub Address,
    pub u32,
    pub u32,
);

pub fn colors_transfer(env: &Env, from: Address, to: Address, colors: Vec<MinerColorAmount>)
```
You would think, and the correct CLI invocation is:
```bash
soroban contract invoke --id $contract_id --source $user1_sk --network Futurenet -- colors_transfer --from $user1_pk --to $user2_pk --colors '[["'$user1_pk'", 0, 1]]'
```
(focus primarily on the `--colors`)

However the `-h` help flag says it's looking for:
```bash
$ soroban contract invoke --id 069023b865700a7aa0b4092f375129acdb396f276a615ff0625985dff314a2c6 -- colors_transfer -h
...
--colors <Array<{ 0: Address, 1: u32, 2: u32 }>>
    Example:
        --colors '[ { "0": "GDIY6AQQ75WMD4W46EYB7O6UYMHOCGQHLAQGQTKHDX4J2DYQCHVCR4W4", "1": 1, "2": 1 } ]'
...
```
Using an indexed object here vs an array won't work and will throw when submitting. Seems that there is some type mismatching going on which I also believe is affecting the typescript binding which currently is generating a broken method for this function.

### PR DESCRIPTION
**Pull request by willemneal**
### What

Add test of a vector of user defined types.

### Why

fixes #735 

### Known limitations

[TODO or N/A]

### CODE REVIEW

**Comment by willemneal** [comment]
@tyvdh if you clone the repo and run `make test` does it pass? It does for me locally.

**Comment by tyvdh** [comment]
Hmm I don't think this addresses the original issue. You're testing a Vec here but the original issue is a Map when it _should_ be a Vec.

**Comment by tyvdh** [comment]
Here's an example of a incorrectly generated typescript binding for a Map that should be a Vec
```ts
function MinerColorAmountToXdr(minerColorAmount?: MinerColorAmount): xdr.ScVal {
    if (!minerColorAmount) {
        return xdr.ScVal.scvVoid();
    }
    // let arr = [
    //     new xdr.ScMapEntry({ key: ((i) => xdr.ScVal.scvSymbol(i))("0"), val: ((i) => addressToScVal(i))(minerColorAmount["0"]) }),
    //     new xdr.ScMapEntry({ key: ((i) => xdr.ScVal.scvSymbol(i))("1"), val: ((i) => xdr.ScVal.scvU32(i))(minerColorAmount["1"]) }),
    //     new xdr.ScMapEntry({ key: ((i) => xdr.ScVal.scvSymbol(i))("2"), val: ((i) => xdr.ScVal.scvU32(i))(minerColorAmount["2"]) })
    // ];
    // return xdr.ScVal.scvMap(arr);
    return xdr.ScVal.scvVec([
        ((i) => addressToScVal(i))(minerColorAmount["0"]),
        ((i) => xdr.ScVal.scvU32(i))(minerColorAmount["1"]),
        ((i) => xdr.ScVal.scvU32(i))(minerColorAmount["2"])
    ])
}
```
The comments are what was generated and what I currently have is what works for `MinerColorAmount` given that type
```rust
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct MinerColorAmount(
    pub Address, // miner
    pub u32,     // color
    pub u32,     // amount
);
```

**Comment by tyvdh** [comment]
Seems like there's a bug where structs with unnamed keys get treated as Maps where they should be Vecs

**Comment by tyvdh** [comment]
struct with named keys should be a `Map`
```rust
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Glyph {
    pub width: u32,
    pub length: u32,
    pub colors: Vec<(Address, Vec<(u32, Vec<u32>)>)>,
}
```

struct with unnamed keys should be a `Vec`
```rust
#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AssetOffer(
    pub BytesN<32>,
    pub Address,
    pub i128,
);
```

**Comment by tsachiherman** [comment]
@willemneal what's the status on this one ? I'd like to either close it or to have it merged.

**Comment by leighmcculloch** [comment]
Closing because of no activity. Please reopen if it still needs actioning.

**Pull request closed without merging**
